//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResourceEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResourceEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLBanHang.Core.Resource.MISAResourceEN", typeof(MISAResourceEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account code does not exist.
        /// </summary>
        public static string AccountIdNotValid {
            get {
                return ResourceManager.GetString("AccountIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts cannot be left blank.
        /// </summary>
        public static string AccountNotNull {
            get {
                return ResourceManager.GetString("AccountNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist.
        /// </summary>
        public static string AccountNotValid {
            get {
                return ResourceManager.GetString("AccountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the authentication code to retrieve the QLBanHang account password.
        /// </summary>
        public static string BodyCodeRecoverPassword {
            get {
                return ResourceManager.GetString("BodyCodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CachedEmployees.
        /// </summary>
        public static string CachedEmployees {
            get {
                return ResourceManager.GetString("CachedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer code already exists in the system.
        /// </summary>
        public static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRecoverPassword.
        /// </summary>
        public static string CodeRecoverPassword {
            get {
                return ResourceManager.GetString("CodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authentication code. Please check again!.
        /// </summary>
        public static string CodeRecoverPasswordNoValid {
            get {
                return ResourceManager.GetString("CodeRecoverPasswordNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer codes cannot be duplicated.
        /// </summary>
        public static string CustomerCodeDuplicate {
            get {
                return ResourceManager.GetString("CustomerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer code does not exist in the system.
        /// </summary>
        public static string CustomerCodeNotFound {
            get {
                return ResourceManager.GetString("CustomerCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The department does not exist in the system.
        /// </summary>
        public static string DepartmentExist {
            get {
                return ResourceManager.GetString("DepartmentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments are not allowed to be vacant.
        /// </summary>
        public static string DepartmentNotEmpty {
            get {
                return ResourceManager.GetString("DepartmentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevMsg:.
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error. Unable to verify login name and password.
        /// </summary>
        public static string DevMsg {
            get {
                return ResourceManager.GetString("DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalidate.
        /// </summary>
        public static string EmailMalformed {
            get {
                return ResourceManager.GetString("EmailMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be left blank.
        /// </summary>
        public static string EmailNotEmpty {
            get {
                return ResourceManager.GetString("EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not exist in the system. Please check again!.
        /// </summary>
        public static string EmailNoValid {
            get {
                return ResourceManager.GetString("EmailNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to already exists in the system, please check again..
        /// </summary>
        public static string EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee codes cannot be left blank.
        /// </summary>
        public static string EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee code does not exist in the system.
        /// </summary>
        public static string EmployeeCodeNotFound {
            get {
                return ResourceManager.GetString("EmployeeCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imported file is not in the correct format.
        /// </summary>
        public static string FileImportMalformed {
            get {
                return ResourceManager.GetString("FileImportMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import files cannot be empty.
        /// </summary>
        public static string FileImportNotNull {
            get {
                return ResourceManager.GetString("FileImportNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/yyyy.
        /// </summary>
        public static string FormatMonthYear {
            get {
                return ResourceManager.GetString("FormatMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:FromMail.
        /// </summary>
        public static string FromMail {
            get {
                return ResourceManager.GetString("FromMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:FromPassword.
        /// </summary>
        public static string FromPassword {
            get {
                return ResourceManager.GetString("FromPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First and last name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave blank is not allowed.
        /// </summary>
        public static string InformationBlank {
            get {
                return ResourceManager.GetString("InformationBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not allowed to be larger than the current date.
        /// </summary>
        public static string InformatonDate {
            get {
                return ResourceManager.GetString("InformatonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account list does not exist.
        /// </summary>
        public static string ListAccountEmpty {
            get {
                return ResourceManager.GetString("ListAccountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information or password is incorrect.
        /// </summary>
        public static string LoginNotSuccess {
            get {
                return ResourceManager.GetString("LoginNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , DevMsg:.
        /// </summary>
        public static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page position cannot be less than 1.
        /// </summary>
        public static string PageIndexNotLessThan1 {
            get {
                return ResourceManager.GetString("PageIndexNotLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of pages cannot be less than 1.
        /// </summary>
        public static string PageSizeNotLessThan1 {
            get {
                return ResourceManager.GetString("PageSizeNotLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be left blank.
        /// </summary>
        public static string PasswordNoEmpty {
            get {
                return ResourceManager.GetString("PasswordNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be left blank.
        /// </summary>
        public static string PasswordNotNull {
            get {
                return ResourceManager.GetString("PasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions cannot be left vacant.
        /// </summary>
        public static string PositionNotEmpty {
            get {
                return ResourceManager.GetString("PositionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The position does not exist in the system.
        /// </summary>
        public static string PostionNotExist {
            get {
                return ResourceManager.GetString("PostionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:RefreshTokenValidityInDays.
        /// </summary>
        public static string RefreshTokenValidityInDays {
            get {
                return ResourceManager.GetString("RefreshTokenValidityInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:SMTPGmail.
        /// </summary>
        public static string SMTPGmail {
            get {
                return ResourceManager.GetString("SMTPGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery code.
        /// </summary>
        public static string SubjectCodeRecoverPassword {
            get {
                return ResourceManager.GetString("SubjectCodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid access token or refresh token.
        /// </summary>
        public static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:TokenValidityInMinutes.
        /// </summary>
        public static string TokenValidityInMinutes {
            get {
                return ResourceManager.GetString("TokenValidityInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMsg:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If an error occurs, please contact QLBanHang for help.
        /// </summary>
        public static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username.
        /// </summary>
        public static string UserNameValid {
            get {
                return ResourceManager.GetString("UserNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:ValidAudience.
        /// </summary>
        public static string ValidAudience {
            get {
                return ResourceManager.GetString("ValidAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:ValidIssuer.
        /// </summary>
        public static string ValidIssuer {
            get {
                return ResourceManager.GetString("ValidIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        public static string XLSX {
            get {
                return ResourceManager.GetString("XLSX", resourceCulture);
            }
        }
    }
}
