//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAExportFileExcel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAExportFileExcel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLBanHang.Core.Resource.MISAExportFileExcel", typeof(MISAExportFileExcel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:AH1.
        /// </summary>
        public static string A1AH1 {
            get {
                return ResourceManager.GetString("A1AH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:AH2.
        /// </summary>
        public static string A1AH2 {
            get {
                return ResourceManager.GetString("A1AH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A1:Q1.
        /// </summary>
        public static string A1Q1 {
            get {
                return ResourceManager.GetString("A1Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A2:Q2.
        /// </summary>
        public static string A2Q2 {
            get {
                return ResourceManager.GetString("A2Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string COLUMN_ADDRESS {
            get {
                return ResourceManager.GetString("COLUMN_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản ngân hàng.
        /// </summary>
        public static string COLUMN_BANKACCOUNT {
            get {
                return ResourceManager.GetString("COLUMN_BANKACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string COLUMN_BANKNAME {
            get {
                return ResourceManager.GetString("COLUMN_BANKNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh ngân hàng.
        /// </summary>
        public static string COLUMN_BRANCH {
            get {
                return ResourceManager.GetString("COLUMN_BRANCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string COLUMN_CODE {
            get {
                return ResourceManager.GetString("COLUMN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string COLUMN_DATEOFBIRTHDAY {
            get {
                return ResourceManager.GetString("COLUMN_DATEOFBIRTHDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp CMND.
        /// </summary>
        public static string COLUMN_DATEOFIDENTITYCARD {
            get {
                return ResourceManager.GetString("COLUMN_DATEOFIDENTITYCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phòng ban.
        /// </summary>
        public static string COLUMN_DEPARTMENTNAME {
            get {
                return ResourceManager.GetString("COLUMN_DEPARTMENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string COLUMN_EMAIL {
            get {
                return ResourceManager.GetString("COLUMN_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string COLUMN_FULLNAME {
            get {
                return ResourceManager.GetString("COLUMN_FULLNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string COLUMN_GENDER {
            get {
                return ResourceManager.GetString("COLUMN_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chứng minh nhân dân.
        /// </summary>
        public static string COLUMN_IDENTIFICATIONCARD {
            get {
                return ResourceManager.GetString("COLUMN_IDENTIFICATIONCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại cố định.
        /// </summary>
        public static string COLUMN_LANDLINE_PHONE {
            get {
                return ResourceManager.GetString("COLUMN_LANDLINE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string COLUMN_PHONENUMBER {
            get {
                return ResourceManager.GetString("COLUMN_PHONENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nới cấp CMND.
        /// </summary>
        public static string COLUMN_PLACE_IDENTIFICATIONCARD {
            get {
                return ResourceManager.GetString("COLUMN_PLACE_IDENTIFICATIONCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên chức danh.
        /// </summary>
        public static string COLUMN_POSITIONNAME {
            get {
                return ResourceManager.GetString("COLUMN_POSITIONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string COLUMN_STATUT {
            get {
                return ResourceManager.GetString("COLUMN_STATUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string COLUMN_STT {
            get {
                return ResourceManager.GetString("COLUMN_STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không được lớn hơn ngày hiện tại.
        /// </summary>
        public static string DateOfBirthNotCurrentDate {
            get {
                return ResourceManager.GetString("DateOfBirthNotCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh không hợp lệ.
        /// </summary>
        public static string DateOfBirthNotValid {
            get {
                return ResourceManager.GetString("DateOfBirthNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại trong hệ thống.
        /// </summary>
        public static string DepartmentNotEmpty {
            get {
                return ResourceManager.GetString("DepartmentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống.
        /// </summary>
        public static string EmployeeCodeAlreadyExist {
            get {
                return ResourceManager.GetString("EmployeeCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên trùng với mã nhân viên khác trong tệp nhập khẩu.
        /// </summary>
        public static string EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép bỏ trống.
        /// </summary>
        public static string EmployeeCodeNotBlank {
            get {
                return ResourceManager.GetString("EmployeeCodeNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên không được phép bỏ trống.
        /// </summary>
        public static string EmployeeNameNotBlank {
            get {
                return ResourceManager.GetString("EmployeeNameNotBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quanlynhanvien.xlsx.
        /// </summary>
        public static string FILENAME {
            get {
                return ResourceManager.GetString("FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể chuyển đổi String sang DateTime.
        /// </summary>
        public static string NotConvertStringToDateTime {
            get {
                return ResourceManager.GetString("NotConvertStringToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy file.
        /// </summary>
        public static string NOTFOUND {
            get {
                return ResourceManager.GetString("NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại trong hệ thống.
        /// </summary>
        public static string PhoneNumberAlreadyExist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT đã trùng với SĐT của nhân viên khác trong tệp nhập khẩu.
        /// </summary>
        public static string PhoneNumberDuplicate {
            get {
                return ResourceManager.GetString("PhoneNumberDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không tồn tại trong hệ thống.
        /// </summary>
        public static string PositionNotEmpty {
            get {
                return ResourceManager.GetString("PositionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R1.
        /// </summary>
        public static string R1 {
            get {
                return ResourceManager.GetString("R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R2.
        /// </summary>
        public static string R2 {
            get {
                return ResourceManager.GetString("R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp lệ.
        /// </summary>
        public static string RecordSuccess {
            get {
                return ResourceManager.GetString("RecordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách bản ghi.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        public static string TYPE {
            get {
                return ResourceManager.GetString("TYPE", resourceCulture);
            }
        }
    }
}
