//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBanHang.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QLBanHang.Core.Resource.MISAResourceVN", typeof(MISAResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản không tồn tại.
        /// </summary>
        public static string AccountIdNotValid {
            get {
                return ResourceManager.GetString("AccountIdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không được phép bỏ trống.
        /// </summary>
        public static string AccountNotNull {
            get {
                return ResourceManager.GetString("AccountNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản không tồn tại.
        /// </summary>
        public static string AccountNotValid {
            get {
                return ResourceManager.GetString("AccountNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên ngân hàng.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Birth {
            get {
                return ResourceManager.GetString("Birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to là mã xác thực lấy lại mật khẩu tài khoản QLBanHang.
        /// </summary>
        public static string BodyCodeRecoverPassword {
            get {
                return ResourceManager.GetString("BodyCodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CachedEmployees.
        /// </summary>
        public static string CachedEmployees {
            get {
                return ResourceManager.GetString("CachedEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kí tự.
        /// </summary>
        public static string Char {
            get {
                return ResourceManager.GetString("Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân.
        /// </summary>
        public static string CMND {
            get {
                return ResourceManager.GetString("CMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại trong hệ thống.
        /// </summary>
        public static string CodeAlreadyExist {
            get {
                return ResourceManager.GetString("CodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeRecoverPassword.
        /// </summary>
        public static string CodeRecoverPassword {
            get {
                return ResourceManager.GetString("CodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã xác thực không hợp lệ. Vui lòng kiểm tra lại!.
        /// </summary>
        public static string CodeRecoverPasswordNoValid {
            get {
                return ResourceManager.GetString("CodeRecoverPasswordNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không được phép trùng.
        /// </summary>
        public static string CustomerCodeDuplicate {
            get {
                return ResourceManager.GetString("CustomerCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng không tồn tại trong hệ thống.
        /// </summary>
        public static string CustomerCodeNotFound {
            get {
                return ResourceManager.GetString("CustomerCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không tồn tại trong hệ thống.
        /// </summary>
        public static string DepartmentExist {
            get {
                return ResourceManager.GetString("DepartmentExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng ban không được phép bỏ trống.
        /// </summary>
        public static string DepartmentNotEmpty {
            get {
                return ResourceManager.GetString("DepartmentNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevMsg:.
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi đăng nhập. Không thể xác minh tên đăng nhập và mật khẩu.
        /// </summary>
        public static string DevMsg {
            get {
                return ResourceManager.GetString("DevMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        public static string EmailMalformed {
            get {
                return ResourceManager.GetString("EmailMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được phép bỏ trống.
        /// </summary>
        public static string EmailNotEmpty {
            get {
                return ResourceManager.GetString("EmailNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không tồn tại trong hệ thống. Vui lòng kiểm tra lại!.
        /// </summary>
        public static string EmailNoValid {
            get {
                return ResourceManager.GetString("EmailNoValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string EmployeeCodeDuplicate {
            get {
                return ResourceManager.GetString("EmployeeCodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sau tiền tố NV- bắt buộc phải nhập chữ số.
        /// </summary>
        public static string EmployeeCodeNotChar {
            get {
                return ResourceManager.GetString("EmployeeCodeNotChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép bỏ trống.
        /// </summary>
        public static string EmployeeCodeNotEmpty {
            get {
                return ResourceManager.GetString("EmployeeCodeNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không tồn tại trong hệ thống.
        /// </summary>
        public static string EmployeeCodeNotFound {
            get {
                return ResourceManager.GetString("EmployeeCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền tố của mã nhân viên bắt buộc là NV- và có ít nhất 1 số đằng sau.
        /// </summary>
        public static string EmployeeCodePrefix {
            get {
                return ResourceManager.GetString("EmployeeCodePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string FEMALE {
            get {
                return ResourceManager.GetString("FEMALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không đúng định dạng.
        /// </summary>
        public static string FileImportMalformed {
            get {
                return ResourceManager.GetString("FileImportMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File nhập khẩu không được bỏ trống.
        /// </summary>
        public static string FileImportNotNull {
            get {
                return ResourceManager.GetString("FileImportNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không đúng định dạng vui lòng kiểm tra lại.
        /// </summary>
        public static string FileNotValid {
            get {
                return ResourceManager.GetString("FileNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/yyyy.
        /// </summary>
        public static string FormatMonthYear {
            get {
                return ResourceManager.GetString("FormatMonthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:FromMail.
        /// </summary>
        public static string FromMail {
            get {
                return ResourceManager.GetString("FromMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:FromPassword.
        /// </summary>
        public static string FromPassword {
            get {
                return ResourceManager.GetString("FromPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép bỏ trống.
        /// </summary>
        public static string InformationBlank {
            get {
                return ResourceManager.GetString("InformationBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép lơn hơn ngày hiện tại.
        /// </summary>
        public static string InformatonDate {
            get {
                return ResourceManager.GetString("InformatonDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài khoản không tồn tại.
        /// </summary>
        public static string ListAccountEmpty {
            get {
                return ResourceManager.GetString("ListAccountEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản hoặc mật khẩu không chính xác.
        /// </summary>
        public static string LoginNotSuccess {
            get {
                return ResourceManager.GetString("LoginNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string MALE {
            get {
                return ResourceManager.GetString("MALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được vượt quá.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;, DevMsg: &quot;.
        /// </summary>
        public static string Msg {
            get {
                return ResourceManager.GetString("Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hợp lệ.
        /// </summary>
        public static string NotValid {
            get {
                return ResourceManager.GetString("NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vị trí trang không được nhỏ hơn 1.
        /// </summary>
        public static string PageIndexNotLessThan1 {
            get {
                return ResourceManager.GetString("PageIndexNotLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trang không được nhỏ hơn 1.
        /// </summary>
        public static string PageSizeNotLessThan1 {
            get {
                return ResourceManager.GetString("PageSizeNotLessThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được phép bỏ trống.
        /// </summary>
        public static string PasswordNoEmpty {
            get {
                return ResourceManager.GetString("PasswordNoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được phép bỏ trống.
        /// </summary>
        public static string PasswordNotNull {
            get {
                return ResourceManager.GetString("PasswordNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không được phép bỏ trống.
        /// </summary>
        public static string PositionNotEmpty {
            get {
                return ResourceManager.GetString("PositionNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ không tồn tại trong hệ thống.
        /// </summary>
        public static string PostionNotExist {
            get {
                return ResourceManager.GetString("PostionNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:RefreshTokenValidityInDays.
        /// </summary>
        public static string RefreshTokenValidityInDays {
            get {
                return ResourceManager.GetString("RefreshTokenValidityInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:Secret.
        /// </summary>
        public static string Secret {
            get {
                return ResourceManager.GetString("Secret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailSettings:SMTPGmail.
        /// </summary>
        public static string SMTPGmail {
            get {
                return ResourceManager.GetString("SMTPGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hồi phục mật khẩu.
        /// </summary>
        public static string SubjectCodeRecoverPassword {
            get {
                return ResourceManager.GetString("SubjectCodeRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thông báo truy cập hoặc mã thông báo làm mới không hợp lệ.
        /// </summary>
        public static string TokenNotValid {
            get {
                return ResourceManager.GetString("TokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:TokenValidityInMinutes.
        /// </summary>
        public static string TokenValidityInMinutes {
            get {
                return ResourceManager.GetString("TokenValidityInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserMsg:.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra hãy liên hệ với QLBanHang đề được giúp đỡ.
        /// </summary>
        public static string UserMessage {
            get {
                return ResourceManager.GetString("UserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên người dùng không hợp lệ.
        /// </summary>
        public static string UserNameValid {
            get {
                return ResourceManager.GetString("UserNameValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:ValidAudience.
        /// </summary>
        public static string ValidAudience {
            get {
                return ResourceManager.GetString("ValidAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT:ValidIssuer.
        /// </summary>
        public static string ValidIssuer {
            get {
                return ResourceManager.GetString("ValidIssuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        public static string XLSX {
            get {
                return ResourceManager.GetString("XLSX", resourceCulture);
            }
        }
    }
}
