const helper = {
  EmployeeCodeDefault: "NV-00001",
  URL: "https://localhost:44307/",
  MApi: {
    Employee: "Employee",
    EmployeeInsert: "Employee/post",
    EmployeeUpdate: "Employee/put",
    EmployeeDelete: "Employee/delete",
    Position: "Position",
    Department: "Department",
    Login: "Account",
    ListAllEmployee: "Employee/GetEmployees",
    GetEmployeeCodeBiggest: "Employee/GetEmployeeCode",
    SendEmail: "Account/forget/sendEmail",
    CheckRecoverCode: "Account/forget/checkCode",
    GetByEmail: "Account/forget/getByEmail",
    UpdatePassword: "Account/forget/reupdatePassword",
    ImportListEmployee: "Employee/import",
    LoginAccount: "Account/login",
    RefreshToken: "Account/refresh-token",
    ForgetPassword: "/forget",
  },
  Emitter: {
    ErrorLogin: "errorLogin",
    SendEvent: "sendEvent",
    ChangePageSize: "changePageSize",
  },
  Emit: {
    HideFormDetailEmployee: "hideFormDetailEmployee",
  },
  LocalStorage: {
    Email: "email",
    Token: "token",
    RefreshToken: "refreshToken",
    Expiration: "expiration",
  },
  Ref: {
    InputSearch: "input_search",
  },
  Router: {
    File: "/file",
    Login: "/login",
    Employee: "/employee",
    ForgetPassword: "/forget",
  },
  TypeIcon: {
    Error: "icon_error",
    Warning: "icon_confirm_warning",
    Success: "icon_successful",
    Question: "icon_confirm_question",
    Delete: "icon_confirm_delete",
  },
  DownLoadFile: {
    Atr: "download",
    NameFile: "listrecord.xlsx",
    ResponseType: "blob",
    Tag: "a",
  },
  Status: {
    Default: 0,
    Insert: 1,
    Update: 2,
    Delete: 3,
    Save: 4,
    Exit: 5,
    UpdateInvoiceFalse: 6,
    DeleteMultiple: 7,
    SaveWhenClose: 8,
    See: 9,
  },
  NameCombobox: {
    Department: "departmentName",
    DepartmentName: "DepartmentName",
    DepartmentId: "DepartmentId",
    Position: "position",
    PositionName: "PositionName",
    PositionId: "PositionId",
  },
  NameInput: {
    EmployeeCode: "employeeCode",
    FullName: "fullName",
    DepartmentName: "departmentName",
    DateOfBirth: "dateOfBirth",
    DateOfIdentityCard: "dateOfIdentityCard",
    IdentificationCard: "identificationCard",
    BankAccount: "bankAccount",
    PhoneNumber: "phoneNumber",
    LandlinePhone: "landlinePhone",
    Email: "email",
    RangeDate: "rangeDate",
    PlaceIdentificationCard: "placeIdentificationCard",
    Address: "address",
    Bank: "bank",
  },
  MPagination: {
    Prev: "prev",
    After: "after",
    Number: "number",
  },
  MKeyBoard: {
    KeyDown: "keydown",
    KeyUp: "keyup",
    Control: "Control",
    D: "d",
    S: "s",
    E: "e",
    One: "1",
    Escape: "Escape",
    SUpper: "S",
  },
};
export default helper;
